## Airline Revenue Management

we show how the airline revenue management problems discussed in this lecture can be solved in R using the "lpSolveAPI" package. This package allows you to solve linear optimization problems in R using the lp_solve library, which is an open-sourced optimization solver. 

If you are solving larger and more complex optimization problems, lp_solve might not be powerful enough to solve your problems. There are other optimization packages available in R that rely on commercial solvers, such as cplexAPI and Rcplex. For more information, see the CRAN Optimization page: (http://cran.us.r-project.org/web/views/Optimization.html)
: requires to install-
```R 
install.packages("lpSolveAPI")
```

In [2]:
library("lpSolveAPI")

Now let's start by solving the simple airline problem with just two decision variables: the number of regular seats to offer, and the number of discount seats to offer. 

The first step is to create a model, which takes as arguments the number of constraints in your model, and the number of decision variables in your model. We have three constraints (one capacity constraint and two demand constraints) and two decision variables.

In [3]:
AirlineSimple = make.lp(3, 2)

 Now we need to set up the constraints and objective. The best way to do this using the lpSolveAPI package is by viewing the constraints in a matrix format. Our objective and three constraints are as follows:
$$ \begin{align}  \text{max} \qquad &       617*R + 238*D \\ 
 \text{subject to} \quad & 1*R +   1*D <= 166 \\
 & 1*R	+   0*D <= 100 \\ 
 & 0*R +   1*D <= 150 
 \end{align}  $$

So the first column in our constraint matrix is c(1,1,0), and the second column in our constraint matrix is c(1,0,1). We also need to indicate that these are less-than-or-equal constraints, and set the right-hand-side values to c(166,100,150):

In [4]:
set.column(AirlineSimple, 1, c(1,1,0))
set.column(AirlineSimple, 2, c(1,0,1))
set.constr.type(AirlineSimple, c("<=","<=","<="))
set.rhs(AirlineSimple, c(166,100,150))

And our objective coefficients are c(617,238):

In [5]:
set.objfn(AirlineSimple, c(617,238))

The default setting is minimize for the objective, so we need to tell R that we are maximizing our objective:

In [6]:
lp.control(AirlineSimple,sense='max')

$anti.degen
[1] "fixedvars" "stalling" 

$basis.crash
[1] "none"

$bb.depthlimit
[1] -50

$bb.floorfirst
[1] "automatic"

$bb.rule
[1] "pseudononint" "greedy"       "dynamic"      "rcostfixing" 

$break.at.first
[1] FALSE

$break.at.value
[1] 1e+30

$epsilon
      epsb       epsd      epsel     epsint epsperturb   epspivot 
     1e-10      1e-09      1e-12      1e-07      1e-05      2e-07 

$improve
[1] "dualfeas" "thetagap"

$infinite
[1] 1e+30

$maxpivot
[1] 250

$mip.gap
absolute relative 
   1e-11    1e-11 

$negrange
[1] -1e+06

$obj.in.basis
[1] TRUE

$pivoting
[1] "devex"    "adaptive"

$presolve
[1] "none"

$scalelimit
[1] 5

$scaling
[1] "geometric"   "equilibrate" "integers"   

$sense
[1] "maximize"

$simplextype
[1] "dual"   "primal"

$timeout
[1] 0

$verbose
[1] "neutral"

If we want to take a look at our model, we can just type:

In [7]:
AirlineSimple

Model name: 
            C1    C2         
Maximize   617   238         
R1           1     1  <=  166
R2           1     0  <=  100
R3           0     1  <=  150
Kind       Std   Std         
Type      Real  Real         
Upper      Inf   Inf         
Lower        0     0         

You should see that there is a row called "Lower" in the model output - the values of zero indicate that our decision variables are constrained to be non-negative, which is the default setting. If you want to change the lower or upper bounds for a decision variable, you can do so with the set.bounds function. (Next week we will learn about integer and binary decision variables - to change a decision variable to one of these types, you can use the set.type function.)

Now we are ready to solve our model:

In [8]:
solve(AirlineSimple)

[1] 0

An output of zero means that the model was successfully solved. You can look at the optimal objective function value or optimal decision variable values with get.objective and get.variables:

In [9]:
get.objective(AirlineSimple)
get.variables(AirlineSimple)

[1] 77408

[1] 100  66

You should get an objective value of 77408 and decision variable values of 100 and 66, just like we did in lecture. 

The following commands set up and solve the more sophisticated airline problem with six decision variables:

In [10]:
AirlineConnecting = make.lp(8,6)

set.column(AirlineConnecting, 1, c(1,1,1,0,0,0,0,0))
set.column(AirlineConnecting, 2, c(1,1,0,1,0,0,0,0))
set.column(AirlineConnecting, 3, c(1,0,0,0,1,0,0,0))
set.column(AirlineConnecting, 4, c(1,0,0,0,0,1,0,0))
set.column(AirlineConnecting, 5, c(0,1,0,0,0,0,1,0))
set.column(AirlineConnecting, 6, c(0,1,0,0,0,0,0,1))
set.constr.type(AirlineConnecting, rep("<=",8))
set.rhs(AirlineConnecting, c(166,166,80,120,75,100,60,110))

set.objfn(AirlineConnecting, c(428,190,642,224,512,190))
lp.control(AirlineConnecting,sense='max')

solve(AirlineConnecting)
get.objective(AirlineConnecting)
get.variables(AirlineConnecting)

$anti.degen
[1] "fixedvars" "stalling" 

$basis.crash
[1] "none"

$bb.depthlimit
[1] -50

$bb.floorfirst
[1] "automatic"

$bb.rule
[1] "pseudononint" "greedy"       "dynamic"      "rcostfixing" 

$break.at.first
[1] FALSE

$break.at.value
[1] 1e+30

$epsilon
      epsb       epsd      epsel     epsint epsperturb   epspivot 
     1e-10      1e-09      1e-12      1e-07      1e-05      2e-07 

$improve
[1] "dualfeas" "thetagap"

$infinite
[1] 1e+30

$maxpivot
[1] 250

$mip.gap
absolute relative 
   1e-11    1e-11 

$negrange
[1] -1e+06

$obj.in.basis
[1] TRUE

$pivoting
[1] "devex"    "adaptive"

$presolve
[1] "none"

$scalelimit
[1] 5

$scaling
[1] "geometric"   "equilibrate" "integers"   

$sense
[1] "maximize"

$simplextype
[1] "dual"   "primal"

$timeout
[1] 0

$verbose
[1] "neutral"

[1] 0

[1] 120514

[1] 80  0 75 11 60 26

You should get an objective function value of 120514 and decision variable values of 80, 0, 75, 11, 60, 26.

For additional examples, we direct you to the [lpSolveAPI User's Guide](http://www.icesi.edu.co/CRAN/web/packages/lpSolveAPI/vignettes/lpSolveAPI.pdf)