# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

class ActivationFunctionType(object):
    NONE = 0
    RELU = 1
    RELU1 = 2
    RELU6 = 3
    TANH = 4
    SIGN_BIT = 5

